name: Publish Package to npmjs
on: workflow_dispatch
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
      - run: npm version patch
      - run: npm push origin main

      - run: git push origin $(git describe --tags --abbrev=0)
